### PR TITLE
loosen Xarray dependency requirements

### PR DESCRIPTION
**Pull request by shaunc**
allow pre-major 1 releases with minor version >= 15

### CODE REVIEW

**Comment by shaunc** [comment]
I decided to give this package a whirl... but I'm using Xarray ^16.1 -- hope this loosening of the requirement is acceptable.

**Comment by astropenguin** [comment]
@shaunc Thank you for reporting this! I think it is nice, but it seems that there is an error around Pyright, which interrupted test workflows (I think your update is not related to the problem). Can I have a time to see what happened?

**Comment by astropenguin** [comment]
@shaunc I am sorry for the late reply. I checked that your update was not related to the fails of tests.
I have a request: could you explicitly specify both boundary like `xarray = ">= 0.15, < 1.0"`?

**Review by astropenguin — CHANGES_REQUESTED** [review]
Could you explicitly specify both boundary like xarray = ">= 0.15, < 1.0"?

**Review by astropenguin — APPROVED** [review]
Looks good to me. Thank you!

**Pull request merged**
